service: download-lambda-docker

provider:
  name: aws
  stage: prod
  region: us-east-1
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:*"
      - "cloudwatch:*"
      - "events:PutRule"
    Resource: 
      - "arn:aws:s3:::noaaweatherdatadaily"
      - "arn:aws:s3:::noaaweatherdatadaily/*"
      - "arn:aws:cloudwatch:*:*:rule/*"
      - "arn:aws:events:us-east-1:813509553407:rule/secondary_download_rule"

functions:
  download:
    timeout: 360
    memorySize: 1024
    image:
      name: img
