service: download-lambda-docker

provider:
  name: aws
  stage: prod
  region: us-east-1
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64
  iamRoleStatements:
    - Effect: "Allow"
      Action:
      - "s3:*"
      - "cloudwatch:*"
      Resource: [
        "arn:aws:s3:::noaaweatherdatadaily",
        "arn:aws:s3:::noaaweatherdatadaily/*",
        "arn:aws:cloudwatch:*:*:rule/*"
      ]

functions:
  download:
    timeout: 360
    memorySize: 1024
    image:
      name: img
    resources:
      Properties:
        UpdateReplacePolicy: "Always"

