service: parse-lambda-docker

provider:
  name: aws
  stage: prod
  region: us-east-1
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64
  iamRoleStatements:
    - Effect: "Allow"
      Action:
      - "s3:*"
      Resource: [
        "arn:aws:s3:::noaaweatherdatadaily",
        "arn:aws:s3:::noaaweatherdatadaily/*"
      ]
functions:
  parse:
    timeout: 600
    memorySize: 1024
    ephemeralStorageSize: 10240
    image:
      name: img
